// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProxyNode(arg1) {
  return window['go']['app']['App']['AddProxyNode'](arg1);
}

export function AddSubscription(arg1) {
  return window['go']['app']['App']['AddSubscription'](arg1);
}

export function ApplyCoreConfiguration(arg1) {
  return window['go']['app']['App']['ApplyCoreConfiguration'](arg1);
}

export function ApplySelectedProxyConfiguration(arg1) {
  return window['go']['app']['App']['ApplySelectedProxyConfiguration'](arg1);
}

export function BeforeClose(arg1) {
  return window['go']['app']['App']['BeforeClose'](arg1);
}

export function ChangeSecurityPIN(arg1, arg2) {
  return window['go']['app']['App']['ChangeSecurityPIN'](arg1, arg2);
}

export function ConfigureSRSSource(arg1) {
  return window['go']['app']['App']['ConfigureSRSSource'](arg1);
}

export function DeleteProxyNode(arg1) {
  return window['go']['app']['App']['DeleteProxyNode'](arg1);
}

export function DeleteSRSSource(arg1) {
  return window['go']['app']['App']['DeleteSRSSource'](arg1);
}

export function DeleteSubscription(arg1) {
  return window['go']['app']['App']['DeleteSubscription'](arg1);
}

export function DisableSecurityPIN(arg1) {
  return window['go']['app']['App']['DisableSecurityPIN'](arg1);
}

export function EnableSecurityPIN(arg1) {
  return window['go']['app']['App']['EnableSecurityPIN'](arg1);
}

export function ExportDiagnosticBundle() {
  return window['go']['app']['App']['ExportDiagnosticBundle']();
}

export function GetApplicationConfigDirectory() {
  return window['go']['app']['App']['GetApplicationConfigDirectory']();
}

export function GetApplicationConfigInfo() {
  return window['go']['app']['App']['GetApplicationConfigInfo']();
}

export function GetAutostartStatus() {
  return window['go']['app']['App']['GetAutostartStatus']();
}

export function GetConnectionObservationEnabled() {
  return window['go']['app']['App']['GetConnectionObservationEnabled']();
}

export function GetCoreStatus() {
  return window['go']['app']['App']['GetCoreStatus']();
}

export function GetDNSPresets() {
  return window['go']['app']['App']['GetDNSPresets']();
}

export function GetDNSSettings() {
  return window['go']['app']['App']['GetDNSSettings']();
}

export function GetIPv6Policy() {
  return window['go']['app']['App']['GetIPv6Policy']();
}

export function GetInterfaceSnapshot() {
  return window['go']['app']['App']['GetInterfaceSnapshot']();
}

export function GetObservations() {
  return window['go']['app']['App']['GetObservations']();
}

export function GetProxySelection() {
  return window['go']['app']['App']['GetProxySelection']();
}

export function GetRecoveryStatus() {
  return window['go']['app']['App']['GetRecoveryStatus']();
}

export function GetRuleProfile(arg1) {
  return window['go']['app']['App']['GetRuleProfile'](arg1);
}

export function GetRuleSettings() {
  return window['go']['app']['App']['GetRuleSettings']();
}

export function GetSRSPresets() {
  return window['go']['app']['App']['GetSRSPresets']();
}

export function GetSecurityStatus() {
  return window['go']['app']['App']['GetSecurityStatus']();
}

export function GetStatus() {
  return window['go']['app']['App']['GetStatus']();
}

export function GetTrafficBudgetStatus() {
  return window['go']['app']['App']['GetTrafficBudgetStatus']();
}

export function InspectProcessRules(arg1) {
  return window['go']['app']['App']['InspectProcessRules'](arg1);
}

export function ListProxyNodes() {
  return window['go']['app']['App']['ListProxyNodes']();
}

export function ListSRSSources() {
  return window['go']['app']['App']['ListSRSSources']();
}

export function ListSubscriptions() {
  return window['go']['app']['App']['ListSubscriptions']();
}

export function PreviewCoreRules(arg1) {
  return window['go']['app']['App']['PreviewCoreRules'](arg1);
}

export function PreviewDiagnosticBundle() {
  return window['go']['app']['App']['PreviewDiagnosticBundle']();
}

export function RecordApplicationLog(arg1, arg2, arg3) {
  return window['go']['app']['App']['RecordApplicationLog'](arg1, arg2, arg3);
}

export function RefreshSRSSource(arg1) {
  return window['go']['app']['App']['RefreshSRSSource'](arg1);
}

export function RefreshSubscription(arg1) {
  return window['go']['app']['App']['RefreshSubscription'](arg1);
}

export function RepairApplicationSettings() {
  return window['go']['app']['App']['RepairApplicationSettings']();
}

export function ResetApplicationSettings() {
  return window['go']['app']['App']['ResetApplicationSettings']();
}

export function ResetInterfaceSelection() {
  return window['go']['app']['App']['ResetInterfaceSelection']();
}

export function ResetTrafficBudget() {
  return window['go']['app']['App']['ResetTrafficBudget']();
}

export function ResetWindowsNetworkStack() {
  return window['go']['app']['App']['ResetWindowsNetworkStack']();
}

export function RunHealthProbe(arg1) {
  return window['go']['app']['App']['RunHealthProbe'](arg1);
}

export function SaveProxyNode(arg1) {
  return window['go']['app']['App']['SaveProxyNode'](arg1);
}

export function SelectInterfaces(arg1, arg2) {
  return window['go']['app']['App']['SelectInterfaces'](arg1, arg2);
}

export function SelectProxyChain(arg1) {
  return window['go']['app']['App']['SelectProxyChain'](arg1);
}

export function SelectProxyNode(arg1) {
  return window['go']['app']['App']['SelectProxyNode'](arg1);
}

export function SelectSingleInterface(arg1) {
  return window['go']['app']['App']['SelectSingleInterface'](arg1);
}

export function SetAutostartEnabled(arg1) {
  return window['go']['app']['App']['SetAutostartEnabled'](arg1);
}

export function SetConnectionObservationEnabled(arg1) {
  return window['go']['app']['App']['SetConnectionObservationEnabled'](arg1);
}

export function SetDNSSettings(arg1) {
  return window['go']['app']['App']['SetDNSSettings'](arg1);
}

export function SetIPv6Policy(arg1) {
  return window['go']['app']['App']['SetIPv6Policy'](arg1);
}

export function SetProxyMode(arg1) {
  return window['go']['app']['App']['SetProxyMode'](arg1);
}

export function SetProxyNodeEgress(arg1, arg2) {
  return window['go']['app']['App']['SetProxyNodeEgress'](arg1, arg2);
}

export function SetProxyNodeFavorite(arg1, arg2) {
  return window['go']['app']['App']['SetProxyNodeFavorite'](arg1, arg2);
}

export function SetRoutingMode(arg1) {
  return window['go']['app']['App']['SetRoutingMode'](arg1);
}

export function SetRuleProfile(arg1, arg2) {
  return window['go']['app']['App']['SetRuleProfile'](arg1, arg2);
}

export function SetRuleSettings(arg1) {
  return window['go']['app']['App']['SetRuleSettings'](arg1);
}

export function SetTrafficBudget(arg1) {
  return window['go']['app']['App']['SetTrafficBudget'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['app']['App']['Shutdown'](arg1);
}

export function SpeedTestProxyNodes(arg1) {
  return window['go']['app']['App']['SpeedTestProxyNodes'](arg1);
}

export function StartTray(arg1) {
  return window['go']['app']['App']['StartTray'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function StopCore() {
  return window['go']['app']['App']['StopCore']();
}

export function TestDNSServer(arg1) {
  return window['go']['app']['App']['TestDNSServer'](arg1);
}

export function TestProxyChain(arg1, arg2) {
  return window['go']['app']['App']['TestProxyChain'](arg1, arg2);
}

export function TestProxyNode(arg1, arg2) {
  return window['go']['app']['App']['TestProxyNode'](arg1, arg2);
}

export function UnlockSecurityVault(arg1) {
  return window['go']['app']['App']['UnlockSecurityVault'](arg1);
}

export function UpdateProxyNode(arg1) {
  return window['go']['app']['App']['UpdateProxyNode'](arg1);
}

export function UpdateSubscription(arg1) {
  return window['go']['app']['App']['UpdateSubscription'](arg1);
}

export function ValidateCoreConfiguration(arg1) {
  return window['go']['app']['App']['ValidateCoreConfiguration'](arg1);
}

export function ValidateSelectedProxyConfiguration(arg1) {
  return window['go']['app']['App']['ValidateSelectedProxyConfiguration'](arg1);
}
