// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {nodes} from '../models';
import {subscriptions} from '../models';
import {config} from '../models';
import {core} from '../models';
import {context} from '../models';
import {rulesets} from '../models';
import {srssets} from '../models';
import {autostart} from '../models';
import {dnssettings} from '../models';
import {interfacemanager} from '../models';
import {main} from '../models';
import {recovery} from '../models';
import {trafficbudget} from '../models';
import {processrules} from '../models';
import {observability} from '../models';

export function AddProxyNode(arg1:nodes.Input):Promise<nodes.Node>;

export function AddSubscription(arg1:subscriptions.Input):Promise<subscriptions.Subscription>;

export function ApplyCoreConfiguration(arg1:config.MVPConfig):Promise<core.Status>;

export function ApplySelectedProxyConfiguration(arg1:config.MVPConfig):Promise<core.Status>;

export function BeforeClose(arg1:context.Context):Promise<boolean>;

export function ConfigureRemoteRuleSet(arg1:rulesets.Source):Promise<rulesets.Source>;

export function ConfigureSRSSource(arg1:srssets.Source):Promise<srssets.Source>;

export function DeleteProxyNode(arg1:string):Promise<void>;

export function DeleteSRSSource(arg1:string):Promise<void>;

export function DeleteSubscription(arg1:string):Promise<void>;

export function ExportDiagnosticBundle():Promise<string>;

export function GetAutostartStatus():Promise<autostart.Status>;

export function GetCoreStatus():Promise<core.Status>;

export function GetDNSPresets():Promise<Array<dnssettings.Preset>>;

export function GetDNSSettings():Promise<dnssettings.Settings>;

export function GetInterfaceSnapshot():Promise<interfacemanager.Snapshot>;

export function GetObservations():Promise<main.ObservationSnapshot>;

export function GetRecoveryStatus():Promise<recovery.Status>;

export function GetRemoteRuleSet():Promise<rulesets.Source>;

export function GetSRSPresets():Promise<Array<srssets.Preset>>;

export function GetStatus():Promise<main.ApplicationStatus>;

export function GetTrafficBudgetStatus():Promise<trafficbudget.Status>;

export function InspectProcessRules(arg1:config.MVPConfig):Promise<Array<processrules.Status>>;

export function ListProxyNodes():Promise<Array<nodes.Node>>;

export function ListSRSSources():Promise<Array<srssets.Source>>;

export function ListSubscriptions():Promise<Array<subscriptions.Subscription>>;

export function PreviewCoreRules(arg1:config.MVPConfig):Promise<Array<config.RulePreview>>;

export function PreviewDiagnosticBundle():Promise<observability.BundlePreview>;

export function RecordApplicationLog(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RefreshRemoteRuleSet():Promise<rulesets.Source>;

export function RefreshSRSSource(arg1:string):Promise<srssets.Source>;

export function RefreshSubscription(arg1:string):Promise<subscriptions.Subscription>;

export function ResetTrafficBudget():Promise<trafficbudget.Status>;

export function RunHealthProbe(arg1:observability.ProbeRequest):Promise<observability.ProbeResult>;

export function SelectInterfaces(arg1:string,arg2:string):Promise<interfacemanager.Snapshot>;

export function SelectProxyNode(arg1:string):Promise<nodes.Node>;

export function SetAutostartEnabled(arg1:boolean):Promise<autostart.Status>;

export function SetDNSSettings(arg1:dnssettings.Settings):Promise<dnssettings.Settings>;

export function SetProxyNodeFavorite(arg1:string,arg2:boolean):Promise<nodes.Node>;

export function SetTrafficBudget(arg1:trafficbudget.Settings):Promise<trafficbudget.Status>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function SpeedTestProxyNodes(arg1:string):Promise<Array<nodes.TestResult>>;

export function StartTray(arg1:Array<number>):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopCore():Promise<core.Status>;

export function TestProxyNode(arg1:string,arg2:string):Promise<nodes.TestResult>;

export function UpdateProxyNode(arg1:nodes.Input):Promise<nodes.Node>;

export function UpdateSubscription(arg1:subscriptions.Input):Promise<subscriptions.Subscription>;

export function ValidateCoreConfiguration(arg1:config.MVPConfig):Promise<void>;

export function ValidateSelectedProxyConfiguration(arg1:config.MVPConfig):Promise<void>;
