// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProxyNode(arg1) {
  return window['go']['main']['App']['AddProxyNode'](arg1);
}

export function AddSubscription(arg1) {
  return window['go']['main']['App']['AddSubscription'](arg1);
}

export function ApplyCoreConfiguration(arg1) {
  return window['go']['main']['App']['ApplyCoreConfiguration'](arg1);
}

export function ApplySelectedProxyConfiguration(arg1) {
  return window['go']['main']['App']['ApplySelectedProxyConfiguration'](arg1);
}

export function BeforeClose(arg1) {
  return window['go']['main']['App']['BeforeClose'](arg1);
}

export function ChangeSecurityPIN(arg1, arg2) {
  return window['go']['main']['App']['ChangeSecurityPIN'](arg1, arg2);
}

export function ConfigureSRSSource(arg1) {
  return window['go']['main']['App']['ConfigureSRSSource'](arg1);
}

export function DeleteProxyNode(arg1) {
  return window['go']['main']['App']['DeleteProxyNode'](arg1);
}

export function DeleteSRSSource(arg1) {
  return window['go']['main']['App']['DeleteSRSSource'](arg1);
}

export function DeleteSubscription(arg1) {
  return window['go']['main']['App']['DeleteSubscription'](arg1);
}

export function DisableSecurityPIN(arg1) {
  return window['go']['main']['App']['DisableSecurityPIN'](arg1);
}

export function EnableSecurityPIN(arg1) {
  return window['go']['main']['App']['EnableSecurityPIN'](arg1);
}

export function ExportDiagnosticBundle() {
  return window['go']['main']['App']['ExportDiagnosticBundle']();
}

export function GetApplicationConfigDirectory() {
  return window['go']['main']['App']['GetApplicationConfigDirectory']();
}

export function GetApplicationConfigInfo() {
  return window['go']['main']['App']['GetApplicationConfigInfo']();
}

export function GetAutostartStatus() {
  return window['go']['main']['App']['GetAutostartStatus']();
}

export function GetConnectionObservationEnabled() {
  return window['go']['main']['App']['GetConnectionObservationEnabled']();
}

export function GetCoreStatus() {
  return window['go']['main']['App']['GetCoreStatus']();
}

export function GetDNSPresets() {
  return window['go']['main']['App']['GetDNSPresets']();
}

export function GetDNSSettings() {
  return window['go']['main']['App']['GetDNSSettings']();
}

export function GetIPv6Policy() {
  return window['go']['main']['App']['GetIPv6Policy']();
}

export function GetInterfaceSnapshot() {
  return window['go']['main']['App']['GetInterfaceSnapshot']();
}

export function GetObservations() {
  return window['go']['main']['App']['GetObservations']();
}

export function GetProxySelection() {
  return window['go']['main']['App']['GetProxySelection']();
}

export function GetRecoveryStatus() {
  return window['go']['main']['App']['GetRecoveryStatus']();
}

export function GetRuleSettings() {
  return window['go']['main']['App']['GetRuleSettings']();
}

export function GetSRSPresets() {
  return window['go']['main']['App']['GetSRSPresets']();
}

export function GetSecurityStatus() {
  return window['go']['main']['App']['GetSecurityStatus']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTrafficBudgetStatus() {
  return window['go']['main']['App']['GetTrafficBudgetStatus']();
}

export function InspectProcessRules(arg1) {
  return window['go']['main']['App']['InspectProcessRules'](arg1);
}

export function ListProxyNodes() {
  return window['go']['main']['App']['ListProxyNodes']();
}

export function ListSRSSources() {
  return window['go']['main']['App']['ListSRSSources']();
}

export function ListSubscriptions() {
  return window['go']['main']['App']['ListSubscriptions']();
}

export function PreviewCoreRules(arg1) {
  return window['go']['main']['App']['PreviewCoreRules'](arg1);
}

export function PreviewDiagnosticBundle() {
  return window['go']['main']['App']['PreviewDiagnosticBundle']();
}

export function RecordApplicationLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['RecordApplicationLog'](arg1, arg2, arg3);
}

export function RefreshSRSSource(arg1) {
  return window['go']['main']['App']['RefreshSRSSource'](arg1);
}

export function RefreshSubscription(arg1) {
  return window['go']['main']['App']['RefreshSubscription'](arg1);
}

export function RepairApplicationSettings() {
  return window['go']['main']['App']['RepairApplicationSettings']();
}

export function ResetApplicationSettings() {
  return window['go']['main']['App']['ResetApplicationSettings']();
}

export function ResetInterfaceSelection() {
  return window['go']['main']['App']['ResetInterfaceSelection']();
}

export function ResetTrafficBudget() {
  return window['go']['main']['App']['ResetTrafficBudget']();
}

export function ResetWindowsNetworkStack() {
  return window['go']['main']['App']['ResetWindowsNetworkStack']();
}

export function RunHealthProbe(arg1) {
  return window['go']['main']['App']['RunHealthProbe'](arg1);
}

export function SaveProxyNode(arg1) {
  return window['go']['main']['App']['SaveProxyNode'](arg1);
}

export function SelectInterfaces(arg1, arg2) {
  return window['go']['main']['App']['SelectInterfaces'](arg1, arg2);
}

export function SelectProxyChain(arg1) {
  return window['go']['main']['App']['SelectProxyChain'](arg1);
}

export function SelectProxyNode(arg1) {
  return window['go']['main']['App']['SelectProxyNode'](arg1);
}

export function SetAutostartEnabled(arg1) {
  return window['go']['main']['App']['SetAutostartEnabled'](arg1);
}

export function SetConnectionObservationEnabled(arg1) {
  return window['go']['main']['App']['SetConnectionObservationEnabled'](arg1);
}

export function SetDNSSettings(arg1) {
  return window['go']['main']['App']['SetDNSSettings'](arg1);
}

export function SetIPv6Policy(arg1) {
  return window['go']['main']['App']['SetIPv6Policy'](arg1);
}

export function SetProxyMode(arg1) {
  return window['go']['main']['App']['SetProxyMode'](arg1);
}

export function SetProxyNodeFavorite(arg1, arg2) {
  return window['go']['main']['App']['SetProxyNodeFavorite'](arg1, arg2);
}

export function SetRuleSettings(arg1) {
  return window['go']['main']['App']['SetRuleSettings'](arg1);
}

export function SetTrafficBudget(arg1) {
  return window['go']['main']['App']['SetTrafficBudget'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['main']['App']['Shutdown'](arg1);
}

export function SpeedTestProxyNodes(arg1) {
  return window['go']['main']['App']['SpeedTestProxyNodes'](arg1);
}

export function StartTray(arg1) {
  return window['go']['main']['App']['StartTray'](arg1);
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function StopCore() {
  return window['go']['main']['App']['StopCore']();
}

export function TestDNSServer(arg1) {
  return window['go']['main']['App']['TestDNSServer'](arg1);
}

export function TestProxyChain(arg1, arg2) {
  return window['go']['main']['App']['TestProxyChain'](arg1, arg2);
}

export function TestProxyNode(arg1, arg2) {
  return window['go']['main']['App']['TestProxyNode'](arg1, arg2);
}

export function UnlockSecurityVault(arg1) {
  return window['go']['main']['App']['UnlockSecurityVault'](arg1);
}

export function UpdateProxyNode(arg1) {
  return window['go']['main']['App']['UpdateProxyNode'](arg1);
}

export function UpdateSubscription(arg1) {
  return window['go']['main']['App']['UpdateSubscription'](arg1);
}

export function ValidateCoreConfiguration(arg1) {
  return window['go']['main']['App']['ValidateCoreConfiguration'](arg1);
}

export function ValidateSelectedProxyConfiguration(arg1) {
  return window['go']['main']['App']['ValidateSelectedProxyConfiguration'](arg1);
}
